---
- name: Configurar IPV6 en loopback
  hosts: CSR1kv
  gather_facts: false
  connection: local

  tasks:
   - name: Agregar IPV6 a loopback 33 
     ios_config:
       parents: "interface loopback 33"
       lines:
         - description IPv6 ADDRESS
         - ipv6 address 3001:ABCD:ABCD:1::1/128
         - ipv6 address FE80::1 link-local
