---
- name: CONFIGURAR IEGRP
  hosts: CSR1kv
  gather_facts: false
  connection: local

  tasks:
  - name: EIGRP NOMBRADA
    ios_config:
      lines:
        - router eigrp REDES
        - address-family ipv4 autonomous-system 101
        - af-interface Loopback 33
        - passive-interface
        - exit-address-family
        - address-family ipv6 autonomous-system 10
        - af-interface Loopback 33
        - passive-interface

  - name: RESULTADO DE EIGRP
    ios_command:
      commands:
        - show running-config | section eigrp 
    register: config
  - name: GUARDAR RESULTADO EIGRP
    copy:
      content: "{{ config.stdout[0] }}"
      dest: "./section1_{{ inventory_hostname }}.txt"
